version: '2'
services:
    memcached:
        image: memcached:alpine
    reviewboard:
        build: ./
        volumes:
            - /var/www/
        depends_on:
            - memcached
        environment:
            - MEMCACHED=memcached:11211
        ports:
            - 8000:8000
